(()=>{
const KEY='family.favorites';
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:'#'}catch{return'#'}};
function activeProfile(){try{const profiles=JSON.parse(localStorage.getItem('family.profiles')||'[]');return localStorage.getItem('family.activeProfile')||profiles[0]?.id||'default'}catch{return'default'}}
function readAll(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function writeAll(items){localStorage.setItem(KEY,JSON.stringify(items))}
function current(){const id=activeProfile();return readAll().filter(f=>(f.profileId||'default')===id).sort((a,b)=>(a.position||0)-(b.position||0))}
function ensureStyles(){if(document.getElementById('favoriteWebsiteStyles'))return;const s=document.createElement('style');s.id='favoriteWebsiteStyles';s.textContent=`.favorites-card{display:none}.favorites-card.active{display:block}.favorite-links{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:11px;margin-top:12px}.favorite-folder-button{display:flex;align-items:center;gap:10px;text-align:left;border:1px solid var(--line);background:#f8f7f3;color:var(--ink);border-radius:16px;padding:13px 14px;font:inherit;font-weight:850;cursor:pointer;min-height:54px}.favorite-folder-button:hover{background:var(--profile-soft,#eef2ed);border-color:var(--profile-soft-strong,#d8e1d9)}.folder-icon{font-size:1.25rem}.folder-meta{display:block;font-size:.72rem;color:var(--muted);font-weight:700;margin-top:1px}.bookmark-dialog{width:min(560px,calc(100% - 28px));border:1px solid var(--line);border-radius:22px;padding:0;color:var(--ink);background:var(--card)}.bookmark-dialog::backdrop{background:rgba(25,32,27,.35);backdrop-filter:blur(2px)}.bookmark-dialog-inner{padding:22px}.bookmark-dialog-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.bookmark-dialog-title{margin:0;font-size:1.35rem}.bookmark-dialog-close{border:0;background:transparent;font-size:27px;cursor:pointer;color:var(--muted)}.folder-sites{display:grid;gap:9px}.folder-site{display:flex;align-items:center;justify-content:space-between;gap:12px;text-decoration:none;color:var(--ink);background:#f8f7f3;border:1px solid var(--line);border-radius:14px;padding:12px 13px;font-weight:800}.folder-site:hover{background:var(--profile-soft,#eef2ed)}.folder-site-host{font-size:.7rem;color:var(--muted);font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:42%}.bookmark-manager{margin-top:12px}.bookmark-row{display:grid;grid-template-columns:1fr 1.4fr .8fr auto;gap:8px;align-items:center;margin:8px 0}.bookmark-row .field{margin:0}.bookmark-delete{border:1px solid var(--line);background:#fff;border-radius:10px;padding:9px 11px;cursor:pointer}.bookmark-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.bookmark-note{font-size:.8rem;color:var(--muted);margin-top:8px}@media(max-width:700px){.favorite-links{grid-template-columns:1fr 1fr}.bookmark-row{grid-template-columns:1fr}.bookmark-delete{justify-self:start}}`;document.head.appendChild(s)}
function ensureCard(){let card=document.getElementById('favoritesCard');if(card)return card;card=document.createElement('section');card.className='card favorites-card';card.id='favoritesCard';card.innerHTML='<p class="eyebrow">Favorite Websites</p><div class="favorite-links" id="favoriteLinks"></div>';const main=document.querySelector('main'),calendar=document.getElementById('calendarCard');main.insertBefore(card,calendar||main.firstElementChild);return card}
function folderGroups(items){const groups=new Map();items.forEach(f=>{const name=(f.folder||'').trim()||'Favorites';if(!groups.has(name))groups.set(name,[]);groups.get(name).push(f)});return [...groups.entries()]}
function openFolder(name,items){document.getElementById('bookmarkFolderDialog')?.remove();const dlg=document.createElement('dialog');dlg.id='bookmarkFolderDialog';dlg.className='bookmark-dialog';dlg.innerHTML=`<div class="bookmark-dialog-inner"><div class="bookmark-dialog-head"><div><p class="eyebrow">Favorite Websites</p><h2 class="bookmark-dialog-title">📁 ${esc(name)}</h2></div><button class="bookmark-dialog-close" type="button" aria-label="Close">×</button></div><div class="folder-sites">${items.map(f=>{const url=safeUrl(f.url);let host='';try{host=new URL(url).hostname.replace(/^www\./,'')}catch{}return `<a class="folder-site" href="${esc(url)}" target="_blank" rel="noreferrer"><span>${esc(f.title||host)}</span><span class="folder-site-host">${esc(host)}</span></a>`}).join('')}</div></div>`;document.body.appendChild(dlg);dlg.querySelector('.bookmark-dialog-close').onclick=()=>dlg.close();dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});dlg.addEventListener('close',()=>dlg.remove());dlg.showModal()}
function render(favorites=current()){ensureStyles();const card=ensureCard(),links=card.querySelector('#favoriteLinks');if(!favorites.length){card.classList.remove('active');links.innerHTML='';return}const groups=folderGroups(favorites);links.innerHTML=groups.map(([name,items],i)=>`<button class="favorite-folder-button" type="button" data-folder-index="${i}"><span class="folder-icon">📁</span><span>${esc(name)}<span class="folder-meta">${items.length} ${items.length===1?'bookmark':'bookmarks'}</span></span></button>`).join('');links.querySelectorAll('.favorite-folder-button').forEach(b=>{b.onclick=()=>{const [name,items]=groups[Number(b.dataset.folderIndex)];openFolder(name,items)}});card.classList.add('active')}
function installManager(){const settings=document.querySelector('#settingsDialog .settings');if(!settings||document.getElementById('bookmarkManager'))return;ensureStyles();const section=document.createElement('div');section.className='setting';section.id='bookmarkManager';section.innerHTML='<h3>Favorite Websites</h3><p class="muted">Bookmarks are saved to this browser for the selected profile. Give bookmarks the same folder name to group them together.</p><div class="bookmark-manager" id="bookmarkRows"></div><div class="bookmark-actions"><button class="btn secondary" id="addBookmark" type="button">＋ Add bookmark</button><label class="btn secondary" for="bookmarkImport" style="cursor:pointer">Import Safari bookmarks</label><input id="bookmarkImport" type="file" accept="text/html,.html" hidden></div><div class="bookmark-note" id="bookmarkStatus"></div>';settings.appendChild(section);drawManager();document.getElementById('addBookmark').onclick=()=>addBookmark();document.getElementById('bookmarkImport').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const html=await file.text(),doc=new DOMParser().parseFromString(html,'text/html'),incoming=[];let position=current().length;doc.querySelectorAll('a[href]').forEach(a=>{const url=(a.getAttribute('href')||'').trim();if(!/^https?:\/\//i.test(url))return;let folder='',node=a.parentElement;while(node){const prev=node.previousElementSibling;if(prev?.tagName==='H3'){folder=prev.textContent.trim();break}node=node.parentElement}incoming.push({id:'bookmark-'+Date.now()+'-'+incoming.length,profileId:activeProfile(),title:a.textContent.trim()||url,url,folder,position:position++})});const all=readAll(),seen=new Set(all.filter(x=>(x.profileId||'default')===activeProfile()).map(x=>x.url)),added=incoming.filter(x=>!seen.has(x.url));writeAll(all.concat(added));document.getElementById('bookmarkStatus').textContent=`Imported ${added.length} bookmarks.`;drawManager();render()}}
function drawManager(){const rows=document.getElementById('bookmarkRows');if(!rows)return;const items=current();rows.innerHTML=items.length?items.map(f=>`<div class="bookmark-row" data-id="${esc(f.id)}"><input class="field bookmark-title" value="${esc(f.title)}" placeholder="Name"><input class="field bookmark-url" value="${esc(f.url)}" placeholder="https://…"><input class="field bookmark-folder" value="${esc(f.folder||'')}" placeholder="Folder"><button class="bookmark-delete" type="button" aria-label="Delete bookmark">🗑</button></div>`).join(''):'<p class="muted">No bookmarks yet.</p>';rows.querySelectorAll('.bookmark-row').forEach(row=>{const save=()=>{const all=readAll(),i=all.findIndex(x=>x.id===row.dataset.id);if(i<0)return;all[i]={...all[i],title:row.querySelector('.bookmark-title').value.trim(),url:row.querySelector('.bookmark-url').value.trim(),folder:row.querySelector('.bookmark-folder').value.trim()};writeAll(all);render()};row.querySelectorAll('input').forEach(i=>i.addEventListener('change',save));row.querySelector('.bookmark-delete').onclick=()=>{writeAll(readAll().filter(x=>x.id!==row.dataset.id));drawManager();render()}})}
function addBookmark(){const all=readAll(),id=activeProfile(),position=current().length,item={id:'bookmark-'+Date.now(),profileId:id,title:'New bookmark',url:'https://',folder:'',position};all.push(item);writeAll(all);drawManager();setTimeout(()=>{const row=document.querySelector(`[data-id="${item.id}"]`);row?.querySelector('.bookmark-title')?.select()},0)}
function load(){render();installManager()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();window.FamilyFavorites={load,render,current,addBookmark};
})();