(()=>{
const KEY='family.sectionLayout';
const DEFAULT=['calendar','favorites','bible'];
const labels={calendar:'Calendar',favorites:'Favorite Websites',bible:'Bible Recap'};
const css=document.createElement('style');css.textContent=`
:root{--bg:#f5f5f7;--card:#fff;--ink:#1d1d1f;--muted:#6e6e73;--line:rgba(0,0,0,.08)}
body{background:var(--bg)!important;color:var(--ink)!important;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text",system-ui,sans-serif!important;letter-spacing:-.01em}
main{width:min(980px,calc(100% - 32px))!important;padding-top:26px!important}
header{margin:0 0 18px!important;text-align:left!important;padding:0 4px}header .eyebrow{display:none}header h1{font-size:clamp(2.2rem,7vw,4.25rem)!important;font-weight:700!important;letter-spacing:-.055em!important;margin-bottom:5px!important}header .sub{font-size:1.05rem}
.profile-switcher{justify-content:flex-start!important;margin:0 0 22px!important;padding:0 4px}.profile-chip{background:transparent!important;border:0!important;padding:8px 13px!important}.profile-chip.active{background:var(--ink)!important;color:#fff!important}
.card{border:0!important;border-radius:28px!important;box-shadow:0 1px 0 rgba(0,0,0,.02),0 8px 30px rgba(0,0,0,.035)!important;padding:28px!important;margin:18px 0!important}.eyebrow{letter-spacing:.04em!important;text-transform:none!important;font-size:.82rem!important}.btn{border-radius:999px!important;padding:10px 16px!important}.btn.secondary{background:#f5f5f7!important}.agenda-day{border:0!important;background:#f5f5f7!important;border-radius:20px!important}.agenda-day.today{border:0!important;box-shadow:none!important}.progress-track{height:7px!important}.gear{top:25px!important;border:0!important;background:rgba(255,255,255,.8)!important;backdrop-filter:blur(16px);box-shadow:0 2px 12px rgba(0,0,0,.06)!important}
#bibleSection{overflow:hidden}#bibleSection>.bible-part{box-shadow:none!important;border-radius:0!important;padding:0!important;margin:0!important;background:transparent!important}#bibleSection>.bible-reading{padding-bottom:25px!important}#bibleSection>.bible-summary{border-top:1px solid var(--line)!important;padding-top:25px!important;font-size:1.08rem}#bibleSection>.bible-summary h2{letter-spacing:-.025em}#bibleSection>.bible-reading #scriptureTitle{font-size:clamp(1.8rem,5vw,2.8rem);letter-spacing:-.045em;margin:8px 0 6px}.bible-section-label{margin-bottom:12px!important}
.layout-manager{display:grid;gap:8px;margin-top:12px}.layout-row{display:grid;grid-template-columns:auto 1fr auto auto;gap:8px;align-items:center;background:#f5f5f7;border-radius:14px;padding:9px 10px}.layout-row button{border:0;background:#fff;border-radius:9px;width:34px;height:34px;cursor:pointer;font-size:16px}.layout-row label{font-weight:750}.layout-row input{width:20px;height:20px}.section-hidden{display:none!important}
@media(max-width:700px){.card{padding:22px!important;border-radius:24px!important}main{width:min(100% - 20px,980px)!important}.layout-row{grid-template-columns:auto 1fr auto auto}}
`;document.head.appendChild(css);
function state(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s&&Array.isArray(s.order))return {order:[...new Set([...s.order,...DEFAULT])].filter(x=>DEFAULT.includes(x)),hidden:Array.isArray(s.hidden)?s.hidden:[]}}catch{}return {order:[...DEFAULT],hidden:[]}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function buildBible(){if(document.getElementById('bibleSection'))return;const header=document.querySelector('header'),reading=document.getElementById('scriptureTitle')?.closest('section.card'),summary=document.getElementById('summaryTitle')?.closest('section.card');if(!reading||!summary||reading===summary)return;const bible=document.createElement('section');bible.className='card';bible.id='bibleSection';bible.dataset.section='bible';const label=document.createElement('p');label.className='eyebrow bible-section-label';label.textContent='Today’s Bible Recap';reading.classList.add('bible-part','bible-reading');summary.classList.add('bible-part','bible-summary');reading.before(bible);bible.append(label,reading,summary);if(header){header.querySelector('h1').textContent='Family Home';const oldSub=header.querySelector('.sub');if(oldSub)oldSub.remove();const sub=document.createElement('p');sub.className='sub';sub.textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});header.appendChild(sub)}}
function tagSections(){document.getElementById('calendarCard')?.setAttribute('data-section','calendar');document.getElementById('favoritesCard')?.setAttribute('data-section','favorites')}
function apply(){tagSections();const s=state(),main=document.querySelector('main');s.order.forEach(id=>{const el=document.querySelector(`[data-section="${id}"]`);if(el)main.appendChild(el)});DEFAULT.forEach(id=>document.querySelector(`[data-section="${id}"]`)?.classList.toggle('section-hidden',s.hidden.includes(id)))}
function manager(){const settings=document.querySelector('#settingsDialog .settings');if(!settings||document.getElementById('layoutManager'))return;const sec=document.createElement('div');sec.className='setting';sec.id='layoutManager';sec.innerHTML='<h3>Home Page Sections</h3><p class="muted">Choose what appears on the home page and put sections in the order you want.</p><div class="layout-manager" id="layoutRows"></div>';settings.appendChild(sec);draw()}
function draw(){const box=document.getElementById('layoutRows');if(!box)return;const s=state();box.innerHTML=s.order.map((id,i)=>`<div class="layout-row" data-id="${id}"><input type="checkbox" ${s.hidden.includes(id)?'':'checked'} aria-label="Show ${labels[id]}"><label>${labels[id]}</label><button type="button" data-move="up" aria-label="Move up" ${i===0?'disabled':''}>↑</button><button type="button" data-move="down" aria-label="Move down" ${i===s.order.length-1?'disabled':''}>↓</button></div>`).join('');box.querySelectorAll('.layout-row').forEach(row=>{row.querySelector('input').onchange=e=>{const x=state(),id=row.dataset.id;x.hidden=e.target.checked?x.hidden.filter(v=>v!==id):[...new Set([...x.hidden,id])];save(x);apply()};row.querySelectorAll('button').forEach(b=>b.onclick=()=>{const x=state(),i=x.order.indexOf(row.dataset.id),j=b.dataset.move==='up'?i-1:i+1;if(j<0||j>=x.order.length)return;[x.order[i],x.order[j]]=[x.order[j],x.order[i]];save(x);apply();draw()})})}
function moveSwitcher(){const sw=document.querySelector('.profile-switcher'),header=document.querySelector('header');if(sw&&header)header.after(sw)}
function init(){buildBible();tagSections();moveSwitcher();apply();manager();setTimeout(()=>{tagSections();apply()},100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.addEventListener('load',()=>{tagSections();apply()});
})();