(()=>{
const KEY='family.sectionLayout';
const DEFAULT=['calendar','favorites','bible'];
const labels={calendar:'Calendar',favorites:'Favorite Websites',bible:'Bible Recap'};
const css=document.createElement('style');css.textContent=`
body{letter-spacing:-.01em}.profile-switcher{justify-content:flex-start!important;margin:0 0 22px!important;padding:0 4px}.profile-chip{background:transparent!important;border:0!important;padding:8px 13px!important}.profile-chip.active{background:var(--ink)!important;color:#fff!important}.layout-manager{display:grid;gap:8px;margin-top:12px}.layout-row{display:grid;grid-template-columns:auto 1fr auto auto;gap:8px;align-items:center;background:#f5f5f7;border-radius:14px;padding:9px 10px}.layout-row button{border:0;background:#fff;border-radius:9px;width:34px;height:34px;cursor:pointer;font-size:16px}.layout-row button:disabled{opacity:.35}.layout-row label{font-weight:750}.layout-row input{width:20px;height:20px}.section-hidden{display:none!important}@media(max-width:700px){.layout-row{grid-template-columns:auto 1fr auto auto}}
`;document.head.appendChild(css);
function state(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s&&Array.isArray(s.order))return {order:[...new Set([...s.order,...DEFAULT])].filter(x=>DEFAULT.includes(x)),hidden:Array.isArray(s.hidden)?s.hidden:[]}}catch{}return {order:[...DEFAULT],hidden:[]}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function tagSections(){document.getElementById('calendarCard')?.setAttribute('data-section','calendar');document.getElementById('favoritesCard')?.setAttribute('data-section','favorites');document.getElementById('bibleSection')?.setAttribute('data-section','bible')}
function apply(){tagSections();const s=state(),main=document.querySelector('main');s.order.forEach(id=>{const el=document.querySelector(`[data-section="${id}"]`);if(el)main.appendChild(el)});DEFAULT.forEach(id=>document.querySelector(`[data-section="${id}"]`)?.classList.toggle('section-hidden',s.hidden.includes(id)))}
function manager(){const settings=document.querySelector('#settingsDialog .settings');if(!settings||document.getElementById('layoutManager'))return;const sec=document.createElement('div');sec.className='setting';sec.id='layoutManager';sec.innerHTML='<h3>Home Page Sections</h3><p class="muted">Choose what appears on the home page and put sections in the order you want.</p><div class="layout-manager" id="layoutRows"></div>';settings.appendChild(sec);draw()}
function draw(){const box=document.getElementById('layoutRows');if(!box)return;const s=state();box.innerHTML=s.order.map((id,i)=>`<div class="layout-row" data-id="${id}"><input type="checkbox" ${s.hidden.includes(id)?'':'checked'} aria-label="Show ${labels[id]}"><label>${labels[id]}</label><button type="button" data-move="up" aria-label="Move up" ${i===0?'disabled':''}>↑</button><button type="button" data-move="down" aria-label="Move down" ${i===s.order.length-1?'disabled':''}>↓</button></div>`).join('');box.querySelectorAll('.layout-row').forEach(row=>{row.querySelector('input').onchange=e=>{const x=state(),id=row.dataset.id;x.hidden=e.target.checked?x.hidden.filter(v=>v!==id):[...new Set([...x.hidden,id])];save(x);apply()};row.querySelectorAll('button').forEach(b=>b.onclick=()=>{const x=state(),i=x.order.indexOf(row.dataset.id),j=b.dataset.move==='up'?i-1:i+1;if(j<0||j>=x.order.length)return;[x.order[i],x.order[j]]=[x.order[j],x.order[i]];save(x);apply();draw()})})}
function moveSwitcher(){const sw=document.querySelector('.profile-switcher'),header=document.querySelector('header');if(sw&&header)header.after(sw)}
function init(){tagSections();moveSwitcher();apply();manager();setTimeout(()=>{tagSections();moveSwitcher();apply()},100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.addEventListener('load',()=>{tagSections();moveSwitcher();apply()});
})();