(()=>{
const PROFILE_KEY='family.profiles',ACTIVE_KEY='family.activeProfile';
const style=document.createElement('style');style.textContent=`.profile-lock-row{margin:12px 0;padding:14px;border:1px solid var(--line);border-radius:16px;background:#f5f5f7}.profile-lock-row label{display:flex;align-items:center;gap:9px;font-weight:750;margin-bottom:10px}.profile-lock-row input[type=checkbox]{width:20px;height:20px}.profile-lock-help{font-size:.8rem;color:var(--muted);margin:0 0 10px}.profile-chip.locked:after{content:' 🔒';font-size:.75em}.profile-unlock{padding:24px;text-align:center}.profile-unlock h2{margin-bottom:6px}.profile-unlock .field{max-width:280px;text-align:center;margin:14px auto;display:block}.profile-unlock-error{min-height:1.4em;color:#b42318;font-size:.85rem}`;document.head.appendChild(style);
function profiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'[]')}catch{return[]}}
function save(list){localStorage.setItem(PROFILE_KEY,JSON.stringify(list))}
async function hash(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function profile(id){return profiles().find(p=>p.id===id)}
function markLocks(){document.querySelectorAll('.profile-chip').forEach(btn=>{const p=profiles().find(x=>x.name===btn.textContent.replace(/ 🔒$/,''));if(p?.passwordHash){btn.classList.add('locked');btn.dataset.profileId=p.id}})}
function ensureDialog(){if(document.getElementById('profileUnlockDialog'))return;const d=document.createElement('dialog');d.id='profileUnlockDialog';d.innerHTML=`<div class="profile-unlock"><p class="eyebrow">Locked profile</p><h2 id="unlockTitle">Enter password</h2><p class="muted">This profile is password protected on this device.</p><form id="unlockForm"><input class="field" id="unlockPassword" type="password" autocomplete="current-password" placeholder="Password" required><div class="profile-unlock-error" id="unlockError"></div><div class="gate-actions"><button class="btn" type="submit">Unlock</button><button class="btn secondary" id="cancelUnlock" type="button">Cancel</button></div></form></div>`;document.body.appendChild(d);document.getElementById('cancelUnlock').onclick=()=>d.close()}
function installSwitchGuard(){ensureDialog();document.addEventListener('click',e=>{const btn=e.target.closest('.profile-chip');if(!btn)return;const list=profiles(),name=btn.textContent.replace(/ 🔒$/,'').trim(),p=list.find(x=>x.id===btn.dataset.profileId)||list.find(x=>x.name===name);if(!p?.passwordHash)return;e.preventDefault();e.stopImmediatePropagation();const d=document.getElementById('profileUnlockDialog'),form=document.getElementById('unlockForm'),input=document.getElementById('unlockPassword'),err=document.getElementById('unlockError');document.getElementById('unlockTitle').textContent=`Unlock ${p.name}`;input.value='';err.textContent='';form.onsubmit=async ev=>{ev.preventDefault();if(await hash(input.value)===p.passwordHash){localStorage.setItem(ACTIVE_KEY,p.id);location.reload()}else{err.textContent='That password is not correct.';input.select()}};d.showModal();setTimeout(()=>input.focus(),50)},true)}
function installSettings(){const setting=document.getElementById('childName')?.closest('.setting');if(!setting||document.getElementById('profileLockEnabled'))return;const activeId=localStorage.getItem(ACTIVE_KEY),p=profile(activeId);if(!p)return;const wrap=document.createElement('div');wrap.className='profile-lock-row';wrap.innerHTML=`<label><input id="profileLockEnabled" type="checkbox" ${p.passwordHash?'checked':''}> Lock this profile with a password</label><p class="profile-lock-help">The password is stored as a one-way hash in this browser only. It keeps casual users from opening the profile; it is not server-side account security.</p><div id="profilePasswordFields" ${p.passwordHash?'':'hidden'}><input class="field" id="profilePassword" type="password" autocomplete="new-password" placeholder="${p.passwordHash?'New password (leave blank to keep current)':'New password'}"><input class="field" id="profilePasswordConfirm" type="password" autocomplete="new-password" placeholder="Confirm password"><button class="btn secondary" id="saveProfilePassword" type="button">${p.passwordHash?'Change password':'Set password'}</button> <span class="status" id="profilePasswordStatus"></span></div>`;const saveProfile=document.getElementById('saveChild');setting.insertBefore(wrap,saveProfile);const enabled=document.getElementById('profileLockEnabled'),fields=document.getElementById('profilePasswordFields'),pw=document.getElementById('profilePassword'),confirmPw=document.getElementById('profilePasswordConfirm'),status=document.getElementById('profilePasswordStatus');enabled.onchange=()=>{fields.hidden=!enabled.checked;if(!enabled.checked&&p.passwordHash){if(confirm('Remove the password lock from this profile?')){const list=profiles(),i=list.findIndex(x=>x.id===activeId);delete list[i].passwordHash;save(list);status.textContent='Lock removed.';markLocks()}else enabled.checked=true}};document.getElementById('saveProfilePassword').onclick=async()=>{if(pw.value.length<4){status.textContent='Use at least 4 characters.';return}if(pw.value!==confirmPw.value){status.textContent='Passwords do not match.';return}const list=profiles(),i=list.findIndex(x=>x.id===activeId);list[i]={...list[i],passwordHash:await hash(pw.value)};save(list);pw.value='';confirmPw.value='';status.textContent='Password lock saved.';enabled.checked=true;fields.hidden=false;markLocks()}}
function init(){markLocks();installSwitchGuard();installSettings();setTimeout(()=>{markLocks();installSettings()},150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();